### ISSUE TITLE
 `Deepl translater` cant check from extensions in albert setting

### ISSUE THREAD

**Issue by fukaoi** [yayuniversal/deepl-plugin-albert#1]
Hi, thank you good extension tool

I installed deepl-plugin-albert and python-dotenv  at manjaro linux.
No error, install success.

I cannot activate deepll-plugin-albert as shown in the attached image.
Did same phenomenon after restart ablert .

What is the cause of this phenomenon?
Please advice me.

![Screenshot_20220713_181500](https://user-images.githubusercontent.com/186659/178701173-07f60460-527a-4668-b15a-a0ddd6b6c909.png)

```
kernel: 5.17.15-1
python: 3.10.5
WM: KDE Plasma
Albert: 0.17.2
```

**Comment by yayuniversal** [comment]
Hi, 
Yeah, apparently a newer version of Albert broke it.

It seems to work if you manually enable the extension in `~/.config/albert/albert.conf`, by adding `deepl_translate` to the `enabled_modules` variable under the `[org.albert.extension.python]` category (and then restart Albert).

Removing the line 24 in the `__init__.py` file from the extension also works:
```python
__py_deps__ = ["python-dotenv"]
```

**Comment by fukaoi** [comment]
@lilianmallardeau 

thank you response. It worked fine.
